### DISCUSSION TITLE
Password to ADMIN ?

### DISCUSSION THREAD

**Discussion by Maniek-o** [balzack/databag#16] [Q&A]
hello ! How to get acces to ADMIN ? I have the same password on configuratiion on istall on unraid.
BUt i cannot log in on webui .
Whats wrong ?

**Comment by balzack** [comment]
The admin password can be set either through the 'ADMIN' environment variable of docker, or if that's not set, it will acquire the password you set the first time you login to the admin portal.

If something has gone wrong, you can find the admin password through console access to the container. Run:
sqlite3 /var/lib/databag/databag.db 
sqlite> select str_value from configs where config_id='token';
<your admin password>

**Reply by gajazura** [reply]
Hello, I'm having the same issue as this. Even tho the admin password has been set and it shows in the config_id='token', entering it in the admin (with the 'cog' in the upper right) section gives the login error "Please confirm your password."

**Reply by balzack** [reply]
Are you accessing the admin through the browser or through the mobile app? If using the mobile app, can you try if the behavior is different with the browser?

**Reply by gajazura** [reply]
Yes, accessing it via a desktop browser. This is what the docker log shows `/internal/api_getNodeConfig.go:12 token not set`

**Reply by balzack** [reply]
Hmm, this error would occur if the 'token' query param is not set in the request. 

Are you using the the docker image published on dockerhub?

Are you comfortable with the browser console? If so do you see this URL request:  https://***/admin/config?token=<your token>

**Reply by gajazura** [reply]
I used this compose in portainer:
```
version: "3.9"
services:
 databag:
   container_name: databag
   image: balzack/databag:latest
   ports:
     - "7000:7000"
   volumes:
     - ./databag-data:/var/lib/databag
   environment:
     - ADMIN=*******
```
It's on a Raspberry Pi 4 running, Raspberry Pi OS Lite 64 bit. 

I don't think I see this `https://***/admin/config?token=` in the browser console.
